PORT_DNS_SERVER = 10053
PORT_HTTP_SHUTDOWN_SERVER = 5003
PORT_HTTP_CHALLENGE_SERVER = 5002
PORT_HTTPS_CERTIFICATE_SERVER = 5001

PATH_PEBBLE_CERTIFICATE = "/home/taddist/ACME/pebble_keys/pebble.minica.pem"
