[[zones]]
host = '*.example.com'
type = 'A'
answer = '1.2.3.3'

[[zones]]
host = 'www.example.com'
type = 'TXT'
answer = 'key_authorization here 2'

[[zones]]
host = 'new.example.com'
type = 'TXT'
answer = 'updated new text'
